"""empty message

Revision ID: 7cdf1fe3700d
Revises: c5a9070fd9a3
Create Date: 2022-10-31 20:01:12.085755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdf1fe3700d'
down_revision = 'c5a9070fd9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('room_quantity', sa.Integer(), nullable=False))
    op.drop_column('request_pool', 'room_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_pool', sa.Column('room_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('flat', 'room_quantity')
    # ### end Alembic commands ###
