"""empty message

Revision ID: 7f72f8d639f1
Revises: ea4216d2c779
Create Date: 2022-11-01 12:02:41.082337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f72f8d639f1'
down_revision = 'ea4216d2c779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('room_quantity_id', sa.Integer(), nullable=False))
    op.drop_constraint('flat_room_quantity_fkey', 'flat', type_='foreignkey')
    op.create_foreign_key(None, 'flat', 'room_quantity', ['room_quantity_id'], ['id'])
    op.drop_column('flat', 'room_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('room_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flat', type_='foreignkey')
    op.create_foreign_key('flat_room_quantity_fkey', 'flat', 'room_quantity', ['room_quantity'], ['id'])
    op.drop_column('flat', 'room_quantity_id')
    # ### end Alembic commands ###
