"""empty message

Revision ID: c5a9070fd9a3
Revises: 
Create Date: 2022-10-31 19:25:55.779583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a9070fd9a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wall_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('request_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('floor_quantity', sa.Integer(), nullable=False),
    sa.Column('wall_material_id', sa.Integer(), nullable=False),
    sa.Column('room_quantity', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wall_material_id'], ['wall_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_pool_id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('kitchen_area', sa.Float(), nullable=False),
    sa.Column('have_balcony', sa.Boolean(), nullable=False),
    sa.Column('minutes_metro_walk', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=22, scale=10), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['request_pool_id'], ['request_pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analogue_flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('kitchen_area', sa.Float(), nullable=False),
    sa.Column('have_balcony', sa.Boolean(), nullable=False),
    sa.Column('minutes_metro_walk', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=22, scale=10), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analogue_flat_corr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analogue_flat_id', sa.Integer(), nullable=False),
    sa.Column('location_corr', sa.Float(), nullable=False),
    sa.Column('floor_corr', sa.Float(), nullable=False),
    sa.Column('total_area_corr', sa.Float(), nullable=False),
    sa.Column('kitchen_area_corr', sa.Float(), nullable=False),
    sa.Column('have_balcony_corr', sa.Float(), nullable=False),
    sa.Column('minutes_metro_walk_corr', sa.Float(), nullable=False),
    sa.Column('condition_corr', sa.Integer(), nullable=False),
    sa.Column('price_corr', sa.Numeric(precision=22, scale=10), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analogue_flat_id'], ['analogue_flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analogue_flat_corr')
    op.drop_table('analogue_flat')
    op.drop_table('flat')
    op.drop_table('request_pool')
    op.drop_table('wall_material')
    op.drop_table('user')
    op.drop_table('segment')
    op.drop_table('condition')
    # ### end Alembic commands ###
