"""empty message

Revision ID: ea4216d2c779
Revises: 7cdf1fe3700d
Create Date: 2022-11-01 12:00:43.749739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4216d2c779'
down_revision = '7cdf1fe3700d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_quantity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'flat', 'room_quantity', ['room_quantity'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flat', type_='foreignkey')
    op.drop_table('room_quantity')
    # ### end Alembic commands ###
